### ISSUE TITLE
Correct text for services description

### ISSUE THREAD

**Issue by austinkocher** [RelevantResearch/Relevant-research-website#4]
Please update the text in the "services" section to the text below. The current text has some misspellings. That's my fault, I didn't provide this text in an easily accessible way the first time.

Website Development

We create custom, professional websites for academic researchers, ensuring their work is presented with clarity, impact, and a seamless online presence that travels with them throughout their careers.

Data Analysis

We provide tailored data analysis services, transforming complex datasets into clear, actionable insights, allowing scholars to focus on their research while we handle the technical challenges.

Public Impact

We craft strategic public impact solutions, helping scholars amplify their research’s visibility and influence by bridging the gap between academia and broader audiences.

**Comment by austinkocher** [comment]
I went ahead and corrected this, hopefully I did it correctly.

**Comment by austinkocher** [comment]
I did not do it correctly. :|

**Comment by Riwajchalise** [comment]
<img width="760" alt="Screenshot 2024-09-19 at 2 56 03 PM" src="https://github.com/user-attachments/assets/d051fd9f-24ea-4cfa-89d8-7ff475685f63">
@bishal784411 please correct typos in services section and be see if you can find typos in other sections of the website aswell.
